FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the FastAPI app files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port FastAPI will run on
EXPOSE 8000

# Command to run the FastAPI app
CMD ["uvicorn", "bridge_api_fastapi.api_server:app", "--host=0.0.0.0", "--port=8000"]