FROM node:16

# Set the working directory
WORKDIR /app

# Copy the Node.js app files
COPY . /app

# Install dependencies
RUN npm install

# Expose the port Node.js will run on
EXPOSE 3000

# Command to run the Node.js app
CMD ["npm", "run", "server"]