FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the Flask app files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port Flask will run on
EXPOSE 5000

# Command to run the Flask app
CMD ["gunicorn", "bridge_api_flask.start_flask:app"]